### ISSUE TITLE
Add usage documentation, possibly simple example application

### ISSUE THREAD

**Issue by Raj123456788** [triaxis-oss/triaxis.Xamarin.BluetoothLE#1]
Hi,
Is there a way you can add an application to solution so that I know which API's to call?

**Comment by ssimek** [comment]
Hi @Raj123456788,

sorry, I definitely won't be able to create an example app soon, I will do my best to put some quickstart notes in the README soon, but I'll try to explain very shortly here - the main "entrypoint" is the IBluetoothLE implementation, implemented by the Platform calsses in the Android and iOS namespaces of their respective nuget versions, meant to be injected e.g. by Xamarin.Forms `DependencyService.Register` method. The rest can then be used solely through the platform-agnostic interfaces.

Checklist:
- register the platform-specific IBluetoothLE implementation in a DI container
- observe Bluetooth adapter status changes (IBluetoothLE.WhenAdapterChanges)
- when you receive an IAdapter instance that has AdapterState.On, you can start observing an IAdapter.Scan for nearby advertising peripherals
- the IAdvertisement-s contain an IPeripheral handle which can be used to IPeripheral.ConnectAsync to a peripheral
- the resulting IPeripheralConnection allows you to perform service and characteristic discovery
- once you have an ICharacteristic, you can use it directly to read and write values and observe notifications

**Comment by Andrew-lll** [comment]
@ssimek Would it be possible for you to either:

1. Create a new maui app using a built in template & register the platform-specific IBluetoothLE implementation in a DI container?  Zip it / put it in the repo. 
2. Add a simple one liner to the readme explaining how to register IBluetoothLE in maui so that there is no question how and in what file to register?

We don't need anything fancy, just the absolute minimum to get it running (in maui).

**Comment by ssimek** [comment]
Hi @andrew-bot ,

There is no built-in support for DI in the MAUI version yet, you can just

```
services.AddSingleton<IBluetoothLE, triaxis.Maui.BluetoothLE.iOS/Android.Platform>();
```

in platform-specific startup code (that's what I'm doing in my projects 😄)

Once you have the IBluetoothLE implementation, the rest is the same as described in my previous comment.

**Comment by sivashakthi** [comment]
In my MAUI project, I added the following line to the MauiProgram.cs

using triaxis.Maui.BluetoothLE;

namespace myaniml;

public static class MauiProgram
{
	public static MauiApp CreateMauiApp()
	{
		var builder = MauiApp.CreateBuilder();
		builder
			.UseMauiApp<App>()
			.ConfigureFonts(fonts =>
			{
				fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
			});
#if __ANDROID__
		builder.Services.AddSingleton< IBluetoothLE, triaxis.Maui.BluetoothLE.Android.Platform>().BuildServiceProvider();
#endif
		return builder.Build();
	}
}

Then, in Mainpage.xaml.cs, if I add the line:
	_btAdapter = DependencyService.Get"IBluetoothLE"(); (replaced <> with "")

it  raises the following error:
System.MissingMethodException: 'No parameterless constructor defined for type 'triaxis.Maui.BluetoothLE.Android.Platform'.'

What am I doing wrong? If I can get my code to work, I'm happy to share the steps in the form of a tutorial that other can use. I'm starting off with a built-in Maui template.

Thanks!

**Comment by ssimek** [comment]
DependencyService is the legacy Xamarin pseudo-container, MAUI uses full-blown Microsoft.Extensions.DependencyInjection. You should be able to just inject it to the MainPage constructor, if you are using the shell, or to the App class you pass to builder.UseMauiApp<App>();

e.g.
```csharp
builder.UseMauiApp<App>();
builder.Services.AddTransient<MainPage>();
builder.Services.AddSingleton<IBluetoothLE, ...>();
```

Also, thanks for the reminder, I really need to add a DI helper method so it becomes just
```csharp
builder.Services.AddBluetoothLE();
```
without strange conditionals.

**Comment by ssimek** [comment]
RC 6 Added a DI extension in the MAUI variants. From now on, it is enough to

```csharp
builder.Services.AddBluetoothLE();
```

to inject the correct `IBluetoothLE` implementation into the container
