### ISSUE TITLE
Unable to load assembly

### ISSUE THREAD

**Issue by sivashakthi** [triaxis-oss/triaxis.Xamarin.BluetoothLE#2]
I'm trying to get this to work under Maui (Preview 14). The assembly throws an exception while trying to create an instance.

System.NotSupportedException: 'Cannot create instance of type 'triaxis.Maui.BluetoothLE.Android.StateBroadcastReceiver': no Java peer type found.'

Has anyone gotten this module to work in .NET MAUI Preview 14?

![image](https://user-images.githubusercontent.com/1831685/160858931-42b5eb6d-3b76-4a6f-9395-57ea6dc24371.png)
![image](https://user-images.githubusercontent.com/1831685/160859670-23a135c0-8f82-4f7d-b7b0-4f73e13d14fe.png)

**Comment by ssimek** [comment]
@sivashakthi I have tried (briefly) and I cannot reproduce this issue. Can you tried with all trimming/shrinking options disabled.

Alternately, can you please attach a small project that reliably triggers the issue?

**Comment by ssimek** [comment]
Closing as not reproducible, please let me know if you find a reproduction scenario with the final MAUI version.
