### ISSUE TITLE
IServiceCollection' does not contain a definition for 'AddBluetoothLE' 

### ISSUE THREAD

**Issue by fweinrebe** [triaxis-oss/triaxis.Xamarin.BluetoothLE#8]
Trying to build the DeviceBrowser example app. Running into this error:

Error	CS1061	'IServiceCollection' does not contain a definition for 'AddBluetoothLE' and no accessible extension method 'AddBluetoothLE' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?)	DeviceBrowser (net6.0-windows10.0.19041.0)	

I tried both adding the Nuget package or including a Project Reference to the 'triaxis.BluetoothLE.Maui' project.  Both methods gave me this error.

Using VS2022 17.5.1

Any help would be appreciated.

**Comment by ssimek** [comment]
Hi @fweinrebe,

I'm sorry, but the library currently supports only common mobile platforms - Xamarin on iOS and Android, and MAUI on iOS, Android and Mac (via Catalyst).

I do not currently plan on supporting Windows, as I have zero experience with Bluetooth on Win.
